version: '3.5'
services:
  ui:
    build:
      context: djing2-elui/
      dockerfile: Dockerfile_release
    container_name: djing2-elui
    stop_grace_period: 1m
    ports:
      - 80:80
    stdin_open: true
    tty: true
    environment:
      - VUE_APP_BASE_API
      - NODE_ENV
    volumes:
      - .:/home/node/app
      - /tmp:/tmp
      - /etc/localtime:/etc/localtime
      - media-data:/var/www/app/media
      - staticfiles:/var/www/app/static


volumes:
  media-data:
  staticfiles:


