# ------------------------- BUILD -------------------------------
FROM node:10

ENV VUE_APP_BASE_API=/api

USER node

ARG APP_DIR=/home/node/app
#ARG NODE_ENV=${NODE_ENV}

RUN mkdir -p ${APP_DIR}
WORKDIR ${APP_DIR}
COPY . .

RUN npm install
RUN npm run build --production

# ------------------------- RELEASE -----------------------------
FROM nginx:alpine
EXPOSE 80

ENV NGINX_SERVER_NAME=localhost

RUN mkdir -p /var/www

COPY ["browsersupp.conf", "expires-hdrs.conf", "/etc/nginx/"]
COPY ["bad_browser.html", "/var/www/"]

COPY --from=0 --chown=nginx:nginx ["/home/node/app/dist", "/var/www/app"]
RUN mkdir -p /var/www/app/media

COPY ["nginx_site.conf", "/etc/nginx/conf.d/default.conf"]
