name: Run build and deploy on push

on:
  push:
    branches:
      - devel
      - master
jobs:
  run_tests:
    runs-on: [ubuntu-latest]

    strategy:
      matrix:
        node-version: [10.x]

    env:
      VUE_APP_BASE_API: /api
      SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
      SERVER_HOST: ${{secrets.SERVER_HOST}}
      SERVER_USER: ${{secrets.SERVER_USER}}

    steps:
        # Чекаутим код
      - uses: actions/checkout@v2
      - name: Install deps
        run: npm install
      - name: Build project
        run: npm run build
      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SERVER_HOST
            User $SERVER_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        shell: bash
      - name: Deploy to server
        run: |
          scp -r ./dist staging:
          ssh staging "sudo /bin/bash ~/bin/apply_djing_ui.sh"
        shell: bash
